### ISSUE TITLE
Migrate all repos from yarn to NPM

### ISSUE THREAD

**Issue by hrescak** [prisma/web-engineering-issues#20]
I'm seeing package lock files and yarn lock files everywhere. Should we set a standard? @nilubava @nikolasburk @2color @mhwelander

**Comment by 2color** [comment]
I don't have a strong preference but I think sticking to one will make it easier when working on multiple projects. In many of our externally facing examples, we use npm so it's probably reasonable to stick to that.

There's also this [tool](https://github.com/imsnif/synp) which helps convert the lock files (`package-lock.json <-> yarn.lock`) from one format to the other.

**Comment by hrescak** [comment]
we'll do npm. website was super easy, but the docs and blog seem to be integrated much more deeply and require some surgery

**Comment by hrescak** [comment]
@nilubava This is amazing!!! Let's add `yarn.lock` to .gitignore and edit the READMEs to make sure we bury it :D
