### ISSUE TITLE
Update copy on prisma.io/jobs page

### ISSUE THREAD

**Issue by meletj** [prisma/web-engineering-issues#28]
**Subtitle on hero image**: Help us to empower developers to build data-intensive applications

**_Challenging technical problem space_ -> Solve challenging technical problems**
At Prisma we are building the data layer for modern applications. If you are fascinated by the software that powers large technology companies, but want the challenges and freedom that come with working in a startup, then a job at Prisma might be for you.

**_Team collaboration and open source_ -> Flexible work environment**
We offer flexible working hours and generous paid time off to meet the needs of employees with different lifestyles, responsibilities, and backgrounds. As long as it fits your team, you have the freedom to build your work schedule and life around each other. 
- [x] Change icon from heart to clock 
- [x] Add logo of Flexa accreditation (SVG logos available here: https://drive.google.com/drive/folders/1pjSPraR0BJv-DvHJ3Kj-oPOkAnhjJY7r?usp=sharing)

**_International team based in Berlin and remote_ -> Fully remote**
We are a remote organization with a globally distributed team. You can work from any location within the UTC -8 to UTC +3 timezones. Choose wherever you are happiest and most productive. 

**_Perks_ -> Benefits**
- Stock options package with a maximum exercise period of 10 years after grant
- 25 vacation days per year in addition to sick leave and public holidays
- 4 mental health days per year
- Access to co-working spaces in your area
- Generous recurring tech budget and subsidy for an ergonomic chair
- [US] 401k matching, health-, vision-, and dental cover.  75% contribution for employees and dependents
- Dedicated People and Operations team
- Yearly company offsite

**Open Positions**
We are constantly looking for talented open-source enthusiasts to join our team. Don’t see your job here? Feel free to reach out to us at jobs@prisma.io

**Comment by meletj** [comment]
There are two further benefits we want to include but I'm waiting for sign off on these. I'll add them as soon as I have them. For the icon to illustrate 'Flexible work environment', I will provide something tomorrow.

**Comment by meletj** [comment]
A few tweaks to the page: 

- Change Perks -> **Benefits**
- **Flexible work environment** updated text: We offer flexible working hours and generous paid time off to meet the needs of employees with different lifestyles and responsibilities. As long as it suits your team, you have the freedom to build your work schedule around your life. 
- Update title and text for **Fully remote organization**: Our team is globally distributed and everyone can work from any location within the UTC -8 to UTC +3 timezones. We want you to choose wherever you are happiest and most productive.
- Move [US] specific benefits to the bottom of the benefits list and change the wording to: [US] 401K matching as well as medical, dental, and vision cover
- Text below **Open Positions** - change first sentence to: We are constantly looking for talented individuals to join our team. 

We still need to add the Flexa logo below the Flexible Working Environment text - would that placement work for both desktop and mobile? Or do we need to find a different placement? Let me know what you think.

**Comment by nilubava** [comment]
Deploy preview: https://deploy-preview-385--prismav8.netlify.app/jobs

@meletj Maybe @julietacurdi or someone from Design can help with the Flexa logo placement? It should work on both desktop and mobile

**Comment by nilubava** [comment]
@meletj I have done all the changes you suggested, except for the Flexa logo. You can ask @luanvdw to help you with this next week, in case you need this page to be published soon :)

**Comment by meletj** [comment]
Additional benefits to add to the list (after mental health days) 
- 20 weeks paid parental leave and 10 days paid time off per year in the event of the sickness of your child
- 6-week paid sabbatical leave after three years

**Comment by luanvdw** [comment]
@meletj I have updated the jobs page with the additional benefits as well as added the Flexa logo underneath the _Flexible work environment_ card.

If you would like to make any changes to the placement and or the colour of the logo (I see they have different variations) - just let me know :)

**Comment by meletj** [comment]
@luanvdw can you publish the page today? /
